### ISSUE TITLE
Bugs in the precision calculation for retrieval  

### ISSUE THREAD

**Issue by nan-wang** [OpenBMB/RAGEval#2]
Following the codes at https://github.com/OpenBMB/RAGEval/blob/493e22ad7ed76139dda0c3fe28fb7d5b9e949996/rageval/evaluation/metrics/rag_metrics/retrieval/precision.py#L12-L15

I built the following example to check the precision implementation, however the output is not as expected.

```python
from rageval.evaluation.metrics.rag_metrics.retrieval.utils import exist_match


def test_exist_match_precision():
    ground_truths = [
        "aaa.",
        "bbb.",
        "ccc.",
    ]
    retrieves = [
        "aaa.",
        "BBB.",
        "ccc.",
        "ddd.",
    ]
    # reference: https://github.com/OpenBMB/RAGEval/blob/493e22ad7ed76139dda0c3fe28fb7d5b9e949996/rageval/evaluation/metrics/rag_metrics/retrieval/precision.py#L12-L15
    result = [exist_match(ground_truths, r, language="en") for r in retrieves]
    assert result == [1, 0, 1, 0]
    # [0, 0, 0, 0] != [1, 0, 1, 0]
```

**Comment by Kunlun-Zhu** [comment]
Hi @nan-wang , thanks for sharing this issue; however, this function actually satisfies our experiment settings. We only consider the matching is valid when all the sentences from groundtruth: List[str] could be found on the retrieves:List[str]

**Comment by Kunlun-Zhu** [comment]
As you can find the code here: https://github.com/OpenBMB/RAGEval/blob/22c4f3be7484e44d5ad152d8770662b383159657/rageval/evaluation/metrics/rag_metrics/retrieval/utils.py#L22

**Comment by Kunlun-Zhu** [comment]
Hi @nan-wang I double check there is some issue on the precision code, since we didn't report precison in the paper anymore, it won't affect the results we present in the paper, and thanks for the pr

**Comment by nan-wang** [comment]
@Kunlun-Zhu Thanks for the quick reply. Anyhow, what is expected way to calculate the precision from your perspective?

I got confused by this line and start digging into the codes. 

 https://github.com/OpenBMB/RAGEval/blob/493e22ad7ed76139dda0c3fe28fb7d5b9e949996/rageval/evaluation/metrics/rag_metrics/retrieval/precision.py#L13

**Comment by nan-wang** [comment]
> however, this function actually satisfies our experiment settings.

Although the precision is not reported in the paper, I am still confused about the implementation.

**Comment by nan-wang** [comment]
okay, i see the PR is merged. <3

**Comment by Kunlun-Zhu** [comment]
@nan-wang  Hi， I believe your implementation is alright, what we found is that, the references recall from the chunk is really hard to match with the groundtruth, since the groundtruth is usually sentence level, but the references could be paragraph level so the precision is usually near 0.
