### ISSUE TITLE
missing schema generation

### ISSUE THREAD

**Issue by lzh00** [OpenBMB/RAGEval#4]
Thank you for sharing your great work~
We are interested with your paper and plan to generate a QA DB in other field. After browsing the code, we can not find schema extraction and summary related code. Are there any problems in this part? or the schema is just designed by experts instead of LLM?

**Comment by Luobots** [comment]
Thanks for your kind words!

First of all, you can find a schema construction prompt template in [here](https://github.com/OpenBMB/RAGEval/blob/main/rageval/article_generation/code/schema/construct.py).

As described in our paper, schema summarization is based on **GPTs on ChatGPT** during that time. You can use GPT creator to create a schema-summarizer GPT and upload some seed documents and ask the model to summarize schema via iterative conversation. (You can either use our prompt template or ask the GPT creator yourself.)

Moreover, if you haven't subscribed to ChatGPT Plus, here are some alternative ways to summarize a schema:

1. Using our prompt template and some tools like langchain to chat based on seed document files.
2. You don't need to upload file, just paste our prompt template to ChatGPT, it has the ability now.
3. You can just upload file in and paste our prompt template in a normal ChatGPT conversation.

**Comment by lzh00** [comment]
Thank you so much for your quick and detail feedback. 
We will have a try~

**Comment by sxxsh** [comment]
> Thanks for your kind words!
> 
> First of all, you can find a schema construction prompt template in [here](https://github.com/OpenBMB/RAGEval/blob/main/rageval/article_generation/code/schema/construct.py).
> 
> As described in our paper, schema summarization is based on **GPTs on ChatGPT** during that time. You can use GPT creator to create a schema-summarizer GPT and upload some seed documents and ask the model to summarize schema via iterative conversation. (You can either use our prompt template or ask the GPT creator yourself.)
> 
> Moreover, if you haven't subscribed to ChatGPT Plus, here are some alternative ways to summarize a schema:
> 
> 1. Using our prompt template and some tools like langchain to chat based on seed document files.
> 2. You don't need to upload file, just paste our prompt template to ChatGPT, it has the ability now.
> 3. You can just upload file in and paste our prompt template in a normal ChatGPT conversation.

生成schema后生成config的code有吗
